# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Derek Jass
email: jazzer36@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog for any ramblings, related to whatever I happen to
  be thinking about or working on at the time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.derekjass.com" # the base hostname & protocol for your site
twitter_username: DerekJass
github_username:  Jazzer360
permalink: pretty

# Build settings
markdown: kramdown
gems:
- jekyll-coffeescript
