# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

### Site settings ###

title: Derek Jass
email: jazzer36@gmail.com
description: >
  A personal blog for any ramblings, related to whatever I happen to
  be thinking about or working on at the time.
url: "http://blog.derekjass.com"
twitter_username: DerekJass
github_username:  Jazzer360

### Build settings ###

future: true

# Plugins
gems:
  - jekyll-coffeescript

# Outputting
permalink: pretty

### Plugin settings ###
sass:
  style: compressed
