// Generated by CoffeeScript 1.10.0
$(function() {
  var yearsSince;
  yearsSince = function(date) {
    return moment().diff(moment(date), 'years');
  };
  $('#myage').text(yearsSince('1983-12-30'));
  $('#harveyage').text(yearsSince('2012-07-25'));
  return $('#marriedyears').text(yearsSince('2010-08-14'));
});
